archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
builds:
  - binary: pulumi-resource-splight
    dir: provider
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -X github.com/pulumi/pulumi-splight/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-splight/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
