name: Release
on: workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  publish_binary:
    name: Publish Provider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true

    - uses: actions/setup-go@v5
      with:
        go-version: 1.21.x

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        args: release --clean
        version: latest

  publish_sdk:
    name: Publish SDKs
    runs-on: ubuntu-latest
    needs: publish_binary
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.nodeversion}}
        registry-url: ${{env.NPM_REGISTRY_URL}}

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.pythonversion}}

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ env.PYPI_PASSWORD }}
        packages_dir: ${{github.workspace}}/sdk/python/bin/dist

    - name: Publish package to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        access: "public"
        token: ${{ env.NPM_TOKEN }}
        package: ${{github.workspace}}/sdk/nodejs/bin/package.json
