name: Tag version
on:
  push:
    branches:
      - master
jobs:
  tag_version:
    runs-on: ubuntu-latest
    name: Create Tag
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v4
      - name: Get version from feature branch
        run: echo "CURRENT_VERSION=v$(cat version)" >> "$GITHUB_ENV"
      - name: Create tag
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ env.CURRENT_VERSION }}
          tag_name: ${{ env.CURRENT_VERSION }}
